// Comprehensive registry of all 50 Indian languages specified for MediKiosk (+ English baseline)
// Includes BCP-47 speech recognition locales, native scripts, regional classification, and TTS acoustic fallbacks.

export const LANGUAGES = [
  {
    code: 'en',
    name: 'English',
    nativeName: 'English',
    speechLang: 'en-IN',
    ttsFallback: 'en-US',
    region: 'Global / India',
    popular: true,
  },
  {
    code: 'hi',
    name: 'Hindi',
    nativeName: 'हिन्दी',
    speechLang: 'hi-IN',
    ttsFallback: 'hi-IN',
    region: 'North / Central India',
    popular: true,
  },
  {
    code: 'bn',
    name: 'Bengali',
    nativeName: 'বাংলা',
    speechLang: 'bn-IN',
    ttsFallback: 'bn-IN',
    region: 'West Bengal / Tripura',
    popular: true,
  },
  {
    code: 'mr',
    name: 'Marathi',
    nativeName: 'मराठी',
    speechLang: 'mr-IN',
    ttsFallback: 'mr-IN',
    region: 'Maharashtra',
    popular: true,
  },
  {
    code: 'te',
    name: 'Telugu',
    nativeName: 'తెలుగు',
    speechLang: 'te-IN',
    ttsFallback: 'te-IN',
    region: 'Andhra Pradesh / Telangana',
    popular: true,
  },
  {
    code: 'ta',
    name: 'Tamil',
    nativeName: 'தமிழ்',
    speechLang: 'ta-IN',
    ttsFallback: 'ta-IN',
    region: 'Tamil Nadu / Puducherry',
    popular: true,
  },
  {
    code: 'gu',
    name: 'Gujarati',
    nativeName: 'ગુજરાતી',
    speechLang: 'gu-IN',
    ttsFallback: 'gu-IN',
    region: 'Gujarat',
    popular: true,
  },
  {
    code: 'ur',
    name: 'Urdu',
    nativeName: 'اردو',
    speechLang: 'ur-IN',
    ttsFallback: 'ur-IN',
    region: 'North / Deccan India',
    direction: 'rtl',
    popular: true,
  },
  {
    code: 'kn',
    name: 'Kannada',
    nativeName: 'ಕನ್ನಡ',
    speechLang: 'kn-IN',
    ttsFallback: 'kn-IN',
    region: 'Karnataka',
    popular: true,
  },
  {
    code: 'or',
    name: 'Odia',
    nativeName: 'ଓଡ଼ିଆ',
    speechLang: 'or-IN',
    ttsFallback: 'or-IN',
    region: 'Odisha',
    popular: true,
  },
  {
    code: 'ml',
    name: 'Malayalam',
    nativeName: 'മലയാളം',
    speechLang: 'ml-IN',
    ttsFallback: 'ml-IN',
    region: 'Kerala / Lakshadweep',
    popular: true,
  },
  {
    code: 'pa',
    name: 'Punjabi',
    nativeName: 'ਪੰਜਾਬੀ',
    speechLang: 'pa-IN',
    ttsFallback: 'pa-IN',
    region: 'Punjab',
    popular: true,
  },
  {
    code: 'as',
    name: 'Assamese',
    nativeName: 'অসমীয়া',
    speechLang: 'as-IN',
    ttsFallback: 'bn-IN',
    region: 'Assam',
    popular: true,
  },
  {
    code: 'mai',
    name: 'Maithili',
    nativeName: 'मैथिली',
    speechLang: 'mai-IN',
    ttsFallback: 'hi-IN',
    region: 'Bihar / Jharkhand',
    popular: false,
  },
  {
    code: 'sat',
    name: 'Santali',
    nativeName: 'ᱥᱟᱱᱛᱟᱲᱤ / संताली',
    speechLang: 'sat-IN',
    ttsFallback: 'bn-IN',
    region: 'Jharkhand / Odisha / WB',
    popular: false,
  },
  {
    code: 'ks',
    name: 'Kashmiri',
    nativeName: 'कॉशुर / کٲشُر',
    speechLang: 'ks-IN',
    ttsFallback: 'ur-IN',
    region: 'Jammu & Kashmir',
    popular: false,
  },
  {
    code: 'ne',
    name: 'Nepali',
    nativeName: 'नेपाली',
    speechLang: 'ne-NP',
    ttsFallback: 'ne-NP',
    region: 'Sikkim / West Bengal',
    popular: true,
  },
  {
    code: 'gon',
    name: 'Gondi',
    nativeName: 'గోండీ / गोंडी',
    speechLang: 'gon-IN',
    ttsFallback: 'te-IN',
    region: 'Madhya Pradesh / Telangana',
    popular: false,
  },
  {
    code: 'sd',
    name: 'Sindhi',
    nativeName: 'سنڌي / सिन्धी',
    speechLang: 'sd-IN',
    ttsFallback: 'hi-IN',
    region: 'Gujarat / Maharashtra',
    popular: false,
  },
  {
    code: 'kok',
    name: 'Konkani',
    nativeName: 'कोंकणी',
    speechLang: 'kok-IN',
    ttsFallback: 'mr-IN',
    region: 'Goa / Maharashtra / Karnataka',
    popular: false,
  },
  {
    code: 'doi',
    name: 'Dogri',
    nativeName: 'डोगरी',
    speechLang: 'doi-IN',
    ttsFallback: 'hi-IN',
    region: 'Jammu & Kashmir',
    popular: false,
  },
  {
    code: 'mni',
    name: 'Manipuri (Meitei)',
    nativeName: 'ꯃꯤꯇꯩꯂꯣꯟ / মৈতৈলোন্',
    speechLang: 'mni-IN',
    ttsFallback: 'bn-IN',
    region: 'Manipur',
    popular: false,
  },
  {
    code: 'dhn',
    name: 'Khandeshi',
    nativeName: 'खानदेशी (अहिराणी)',
    speechLang: 'dhn-IN',
    ttsFallback: 'mr-IN',
    region: 'Maharashtra',
    popular: false,
  },
  {
    code: 'kru',
    name: 'Kurukh',
    nativeName: 'कुड़ुख़ (ओरांव)',
    speechLang: 'kru-IN',
    ttsFallback: 'hi-IN',
    region: 'Jharkhand / Chhattisgarh',
    popular: false,
  },
  {
    code: 'kha',
    name: 'Khasi',
    nativeName: 'Ka Ktien Khasi',
    speechLang: 'kha-IN',
    ttsFallback: 'en-IN',
    region: 'Meghalaya',
    popular: false,
  },
  {
    code: 'brx',
    name: 'Bodo',
    nativeName: 'बड़ो',
    speechLang: 'brx-IN',
    ttsFallback: 'as-IN',
    region: 'Assam',
    popular: false,
  },
  {
    code: 'grt',
    name: 'Garo',
    nativeName: 'A·chik / Garo',
    speechLang: 'grt-IN',
    ttsFallback: 'en-IN',
    region: 'Meghalaya / Assam',
    popular: false,
  },
  {
    code: 'unr',
    name: 'Mundari',
    nativeName: 'मुण्डारी (Mundari)',
    speechLang: 'unr-IN',
    ttsFallback: 'hi-IN',
    region: 'Jharkhand / Odisha',
    popular: false,
  },
  {
    code: 'hoc',
    name: 'Ho',
    nativeName: 'वारंग क्षिति / हो',
    speechLang: 'hoc-IN',
    ttsFallback: 'hi-IN',
    region: 'Jharkhand / Odisha',
    popular: false,
  },
  {
    code: 'kxu',
    name: 'Kui',
    nativeName: 'କୁଇ (Kui)',
    speechLang: 'kxu-IN',
    ttsFallback: 'or-IN',
    region: 'Odisha',
    popular: false,
  },
  {
    code: 'kfq',
    name: 'Korku',
    nativeName: 'कोरकू (Korku)',
    speechLang: 'kfq-IN',
    ttsFallback: 'hi-IN',
    region: 'Madhya Pradesh / Maharashtra',
    popular: false,
  },
  {
    code: 'hlb',
    name: 'Halbi',
    nativeName: 'हलबी (Halbi)',
    speechLang: 'hlb-IN',
    ttsFallback: 'hi-IN',
    region: 'Bastar / Chhattisgarh',
    popular: false,
  },
  {
    code: 'mrg',
    name: 'Miri (Mising)',
    nativeName: 'Mising / Miri',
    speechLang: 'mrg-IN',
    ttsFallback: 'as-IN',
    region: 'Assam / Arunachal',
    popular: false,
  },
  {
    code: 'mjw',
    name: 'Karbi',
    nativeName: 'Karbi (কার্বি)',
    speechLang: 'mjw-IN',
    ttsFallback: 'as-IN',
    region: 'Assam',
    popular: false,
  },
  {
    code: 'kff',
    name: 'Koya',
    nativeName: 'కోయ (Koya)',
    speechLang: 'kff-IN',
    ttsFallback: 'te-IN',
    region: 'Telangana / Andhra Pradesh',
    popular: false,
  },
  {
    code: 'njo',
    name: 'Ao',
    nativeName: 'Ao Chungli',
    speechLang: 'njo-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'stv',
    name: 'Sema (Sümi)',
    nativeName: 'Sümi (Sema)',
    speechLang: 'stv-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'njm',
    name: 'Angami',
    nativeName: 'Tenyidie (Angami)',
    speechLang: 'njm-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'nbe',
    name: 'Konyak',
    nativeName: 'Konyak',
    speechLang: 'nbe-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'nmf',
    name: 'Tangkhul',
    nativeName: 'Tangkhul Naga',
    speechLang: 'nmf-IN',
    ttsFallback: 'en-IN',
    region: 'Manipur / Nagaland',
    popular: false,
  },
  {
    code: 'lus',
    name: 'Mizo',
    nativeName: 'Mizo ṭawng',
    speechLang: 'lus-IN',
    ttsFallback: 'en-IN',
    region: 'Mizoram',
    popular: false,
  },
  {
    code: 'tcz',
    name: 'Thado',
    nativeName: 'Thadou Kuki',
    speechLang: 'tcz-IN',
    ttsFallback: 'en-IN',
    region: 'Manipur / Assam',
    popular: false,
  },
  {
    code: 'njh',
    name: 'Lotha',
    nativeName: 'Lotha Naga',
    speechLang: 'njh-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'rah',
    name: 'Rabha',
    nativeName: 'Rabha (রাভা)',
    speechLang: 'rah-IN',
    ttsFallback: 'as-IN',
    region: 'Assam / Meghalaya',
    popular: false,
  },
  {
    code: 'nri',
    name: 'Chokri',
    nativeName: 'Chokri (Chakhesang)',
    speechLang: 'nri-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'nph',
    name: 'Phom',
    nativeName: 'Phom Naga',
    speechLang: 'nph-IN',
    ttsFallback: 'en-IN',
    region: 'Nagaland',
    popular: false,
  },
  {
    code: 'njz',
    name: 'Nyishi',
    nativeName: 'Nyishi (Dafla)',
    speechLang: 'njz-IN',
    ttsFallback: 'en-IN',
    region: 'Arunachal Pradesh',
    popular: false,
  },
  {
    code: 'lep',
    name: 'Lepcha',
    nativeName: 'Róng (Lepcha)',
    speechLang: 'lep-IN',
    ttsFallback: 'ne-NP',
    region: 'Sikkim / Kalimpong',
    popular: false,
  },
  {
    code: 'lif',
    name: 'Limbu',
    nativeName: 'Limbu (ᤕᤠᤰᤌᤢᤱ)',
    speechLang: 'lif-IN',
    ttsFallback: 'ne-NP',
    region: 'Sikkim / West Bengal',
    popular: false,
  },
  {
    code: 'bix',
    name: 'Bhumij',
    nativeName: 'भूमिज (Bhumij)',
    speechLang: 'bix-IN',
    ttsFallback: 'bn-IN',
    region: 'Jharkhand / Odisha / WB',
    popular: false,
  },
  {
    code: 'sa',
    name: 'Sanskrit',
    nativeName: 'संस्कृतम्',
    speechLang: 'sa-IN',
    ttsFallback: 'hi-IN',
    region: 'Pan-India Classical',
    popular: true,
  },
];

// Helper to look up language metadata by code
export const getLanguageByCode = (code) => {
  if (!code) return LANGUAGES[0];
  const found = LANGUAGES.find((l) => l.code === code || l.code.toLowerCase() === code.toLowerCase());
  return found || LANGUAGES[0];
};
